language: c
os: linux
sudo: false
dist: trusty
compiler:
  - m68k-atari-mint-gcc

addons:
  apt:
    sources:
      - sourceline: 'ppa:vriviere/ppa'
    packages:
      - cross-mint-essential
      - cflib-m68k-atari-mint

env:
  global:
    - BINTRAY_USER="mikrosk"
    # this creates variable BINTRAY_API_KEY="<api key>"
    - secure: "bMkAkMFU2BqPBUAj2BqmgR+eScOs69wNxTFc4rMwekQxejC99NWefgdPsM5m3OUmj0T7KVPTwfbBJymVHk2ISd5ZehynITA1aUI6WAX7HBGTfeaCQHPd8zazDeY9BasVIP3ddmuM7lHrzg7zG1bmWT2cxAt9+G82TNDemZGVXhtmHP5wQV8Uwg/uIkSdeUEq+fxU5DSttTusSMrNrHGkHLPGVzfERPo85qs3yfGcVH5BKOM32PJBW+sM8nAMwxsbT4ModY5T8kM8zM2sa0TzBH3AIwh3ss32KAd/fpZwvMnAEJsY40g6xQfd/CWQYXxW2OkohqpPUt8X+8nVIRZbbIT7GjqfI3wOSzBDenZ9z0ZVDuVvWhRDIFeYyTkBa9PRZVrJtxBSgkVX+6K5PRxykIDIoqmxXyan+GT70WC35HCKhOYTwXhrAX90hmm+xkCfe85rIsDCjb1P/TtELO1NZS+SjgFRDD9TC7FUtt/ioYPbnwZ64zmyt4ptxEPLCjCqmT88Jx7S2hkGSjuHLlr0S8I7vY6kVlJn4ZUfCnZuM9HZGuIryOjyVLisoEa4SpX0ZpACBdnN8qvjIYLLV3Ux+cc/96n7NqEA+NE5LgT6C83Otg5ooYtvH9MtS4K6TdaDMGCmGkmx45WcCibRMInsHC4v03alwnP7G+qUFX1DUQA="
  matrix:
    #- OLD_BUILD=0 SCRIPT_BRANCH="freemint-1.18"
    - OLD_BUILD=1 SCRIPT_BRANCH="freemint-1.18-raw"

# If before_install, install or before_script return a non-zero exit code, the build is errored and stops immediately.
before_install:
  - git clone --depth=1 --branch=${SCRIPT_BRANCH} https://github.com/freemint/travis-scripts.git .travis
  - if [ -x .travis/before_install.sh ]; then ./.travis/before_install.sh; else true; fi

install:
  - if [ -x .travis/install.sh ]; then ./.travis/install.sh; else true; fi

before_script:
  - if [ -x .travis/before_script.sh ]; then ./.travis/before_script.sh; else true; fi

# If script returns a non-zero exit code, the build is failed, but continues to run before being marked as failed.
script:
  - if [ -x .travis/script.sh ]; then ./.travis/script.sh; else true; fi
# The exit code of after_success, after_failure, after_script and subsequent stages do not affect the build result.
# However, if one of these stages times out, the build is marked as a failure.
after_success:
  - if [ -x .travis/after_success.sh ]; then ./.travis/after_success.sh; else true; fi
after_failure:
  - if [ -x .travis/after_failure.sh ]; then ./.travis/after_failure.sh; else true; fi

# A non-zero exit code in this phase will mark the build as errored.
before_deploy:
  - if [ -x .travis/before_deploy.sh ]; then ./.travis/before_deploy.sh; else true; fi

deploy:
  edge:
    branch: v1.8.47
  provider: bintray
  file: ".travis/bintray.desc"
  user: "${BINTRAY_USER}"
  key: "${BINTRAY_API_KEY}"
  skip_cleanup: true
  on:
    branch: freemint-1_18
    repo: freemint/freemint

after_deploy:
  - if [ -x .travis/after_deploy.sh ]; then ./.travis/after_deploy.sh; else true; fi

after_script:
  - if [ -x .travis/after_script.sh ]; then ./.travis/after_script.sh; else true; fi
